# Home page profile
[home]
  [home.profile]
    enable = true
    avatarURL = ""
    title = ""
    subtitle = "Korean culture stories for global readers"
    typeit = false
    social = false

# Page config
[page]
  # Table of the contents config
  [page.toc]
    enable = true
    keepStatic = false
    auto = true

# Analytics config
[analytics]
  enable = true
  [analytics.google]
    id = "G-4EZL6ZHWS5"
    anonymizeIP = true
