baseURL = "https://k-vibe.net/"
defaultContentLanguage = "en"
title = "K-VIBE"
theme = "DoIt"

enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
